<?php

/**
 * @wordpress-plugin
 * Plugin Name:       Kntnt Slim SEO Disable Taxonomy Sitemap
 * Plugin URI:        https://www.kntnt.com/
 * Description:       Disables output of taxonomies in the sitemap generated by Slim SEO.
 * Version:           1.1.0
 * Author:            Thomas Barregren
 * Author URI:        https://www.kntnt.com/
 * License:           GPL-3.0+
 * License URI:       http://www.gnu.org/licenses/gpl-3.0.txt
 */

add_filter( 'slim_seo_sitemap_taxonomies', '__return_empty_array' );
